Randomization of subjects for 2-arm designs
Cytel-Inc/CyneRgy pull request #159
Opened 2024-05-22 08:49 UTC by slahoti17

The commit includes 3 methods to Randomize the patients / subjects in two arm designs.
1. Randomization using a random number generated from Uniform(0,1) distribution.
2. Randomization using sample() function in base R package
3. Block Randomization using pbrPar() function from "randomizeR" package in R  

Please go through the "Description.Rmd" file to understand the steps for each method.

2024-05-28 17:54 UTC, kwathen requested changes
Please review and address all comments.   
Overall:
1. If you are using R Studio please make sure to check spelling as there are a few mistakes noted in comments.
2. Please follow the style guide mentioned https://cytel-inc.github.io/CyneRgy/articles/ContibutingToCyneRgy.html  - Exception is that the parameters that are sent from East that do follow the style are okay and don't need to be assigned to a variable name to make it follow,  eg no need to
dNumArms <- NumArms # NumArms is fine to use directly. 
3. Please use the assignment operator <- for assignment rather than =

2024-05-29 05:14 UTC, slahoti17 commented on inst/Examples/RandomizeSubjects/Description.Rmd
> +The function named "BlockRandomizationSubjectsUsingRPackage.R" in the file makes use of pbrPar() function from the library named "randomizeR" to perform the Block randomization.
Sure Kyle, I will confirm with Anoop

2024-05-29 05:47 UTC, slahoti17 commented on inst/Examples/RandomizeSubjects/Rcode/RandomizationSubjectsUsingSampleFunctionInR.R
> +    vSampleSizeArmWise            <- c( round( dNumSub * dAllocFraction[ 1 ]), dNumSub - round( dNumSub * dAllocFraction[ 1 ] ) )
Experimental arm expected sample size** = (NumSub - round( NumSub * dAllocFraction[ 1 ]).

So this will ensure sum( vSampleSizeArmWise ) = NumSub

2024-05-29 05:47 UTC, slahoti17 commented on inst/Examples/RandomizeSubjects/Rcode/BlockRandomizationSubjectsUsingRPackage.R
> +# UserParam = It is the list of Block lengths. So if a user wants randomization sampling to be done in "b" blocks, provide a list of b components such that each component represnts the length of bloc
Noted, thanks for pointing it out

2024-05-29 05:48 UTC, slahoti17 commented on inst/Examples/RandomizeSubjects/Rcode/BlockRandomizationSubjectsUsingRPackage.R
> +# For example - for 2 blocks, UserParam <- list(x = 20, y = 10) where 20 is the length of first block and 10 is the length of second block.
Checked, this is working. Thanks

2024-05-29 05:49 UTC, slahoti17 commented on inst/Examples/RandomizeSubjects/Rcode/RandomizationSubjectsUsingUniformDistribution.R
> +    Error 	= 0
corrected.

2024-05-29 05:49 UTC, slahoti17 commented on inst/Examples/RandomizeSubjects/Rcode/RandomizationSubjectsUsingSampleFunctionInR.R
> +    retval[ vTreatmentArmIndex ]  =  1
corrected.

2024-05-29 05:49 UTC, slahoti17 commented on inst/Examples/RandomizeSubjects/Rcode/BlockRandomizationSubjectsUsingRPackage.R
> +BlockRandomizationSubjectsUsingRPackage <- function( NumSub, NumArms, AllocRatio, UserParam = NULL )
Updated.

2024-05-29 05:49 UTC, slahoti17 commented on inst/Examples/RandomizeSubjects/Rcode/LibraryrandomizeR.R
> +LoadrandomizeR <- function( Seed )
updated

2024-06-06 13:54 UTC, kwathen approved these changes

2024-06-06 13:56 UTC, kwathen commented
Fixes #153

2024-06-06 13:56 UTC, merged